### ISSUE TITLE
Crash after activating

### ISSUE THREAD

**Issue by DocSniper** [renyuneyun/CamCov#1]
08-02 13:41:59.797 I/ActivityManager(828): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=ryey.camcov/.SettingsActivity bnds=[333,1388][489,1544](has extras)} from uid 10021 on display 0
08-02 13:41:59.827 I/ActivityManager(828): Start proc 30865:ryey.camcov/u0a285 for activity ryey.camcov/.SettingsActivity
08-02 13:41:59.901 W/System  (30865): ClassLoader referenced unknown path: /data/app/ryey.camcov-1/lib/arm
08-02 13:42:00.096 I/ActivityManager(828): Displayed ryey.camcov/.SettingsActivity: +288ms
08-02 13:42:01.927 E/AndroidRuntime(30865): Process: ryey.camcov, PID: 30865
08-02 13:42:01.927 E/AndroidRuntime(30865): java.lang.RuntimeException: Unable to create service ryey.camcov.OverlayService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3dbeec4 -- permission denied for this window type
08-02 13:42:01.927 E/AndroidRuntime(30865):     at ryey.camcov.OverlayService.onCreate(Unknown Source)
08-02 13:42:01.929 W/ActivityManager(828):   Force finishing activity ryey.camcov/.SettingsActivity
08-02 13:42:02.449 W/

**Comment by renyuneyun** [comment]
I guess you are using Android M, right?

I found a same issue here http://stackoverflow.com/questions/7569937/unable-to-add-window-android-view-viewrootw44da9bc0-permission-denied-for-t#answer-34061521 .

Seems that you need to manually grant (allow) this app the permission 'Draw over other apps'.

I'll add a prompt for this soon.

**Comment by DocSniper** [comment]
Yes you are right, I'm on M. 
And thanks for mentioning the permission 'Draw over other apps', now it's working.  :-)
