### ISSUE TITLE
Inverted picture.

### ISSUE THREAD

**Issue by crhy** [renyuneyun/CamCov#7]
I'm on a nexus 5x. It's inverted on the horizontal axis.

**Comment by renyuneyun** [comment]
I'm aware of part of this issue, since I just hard-coded the rotation rather than writing some logic to set it.
But it's strange for your case.

Anyway, I'll try to figure that out if I'm free.

**Comment by crhy** [comment]
A toggle switch in settings would work if that's easier. :)

**Comment by renyuneyun** [comment]
Finally got time to do this... (Actually I wasted time on unnecessary methods)

v0.5 added inverting ability :)

**Comment by crhy** [comment]
Awesome!  Thanks!

rhY
